export const ActionTypes = {
  /*
    Example Entity Actions
  */
  REQUEST_LOAD_EXAMPLES: 'REQUEST_LOAD_EXAMPLES',
  RECEIVE_LOAD_EXAMPLES_SUCCESS: 'RECEIVE_LOAD_EXAMPLES_SUCCESS',
  RECEIVE_LOAD_EXAMPLES_ERROR: 'RECEIVE_LOAD_EXAMPLES_ERROR',


  /*
    Raw API Action
  */
  CALL_API: 'CALL_API'
};
